<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWRTUNyM\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWRTUNyM/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWRTUNyM.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerWRTUNyM\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerWRTUNyM\srcProdProjectContainer(array(
    'container.build_hash' => 'WRTUNyM',
    'container.build_id' => '7fe12647',
    'container.build_time' => 1522960962,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWRTUNyM');
