<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0W1h0wH\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0W1h0wH/srcProdProjectContainer.php') {
    touch(__DIR__.'/Container0W1h0wH.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\Container0W1h0wH\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \Container0W1h0wH\srcProdProjectContainer(array(
    'container.build_hash' => '0W1h0wH',
    'container.build_id' => '4f53d482',
    'container.build_time' => 1523979668,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0W1h0wH');
