<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.fSCnt1p' shared service.

return $this->privates['service_locator.fSCnt1p'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('carsBrandRepository' => function (): ?\App\Repository\CarsBrandRepository {
    return ($this->privates['App\Repository\CarsBrandRepository'] ?? $this->load('getCarsBrandRepositoryService.php'));
}));
