<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.CikYYQ2' shared service.

return $this->privates['service_locator.CikYYQ2'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('carsModelRepository' => function (): ?\App\Repository\CarsModelRepository {
    return ($this->privates['App\Repository\CarsModelRepository'] ?? $this->load('getCarsModelRepositoryService.php'));
}));
