<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\CarsBrandController:index' => function () {
    return ($this->privates['service_locator.fSCnt1p'] ?? $this->load('getServiceLocator_FSCnt1pService.php'));
}, 'App\\Controller\\CarsModelController:index' => function () {
    return ($this->privates['service_locator.CikYYQ2'] ?? $this->load('getServiceLocator_CikYYQ2Service.php'));
}, 'App\\Controller\\SecurityController:loginAction' => function () {
    return ($this->privates['service_locator.ltE88OR'] ?? $this->load('getServiceLocator_LtE88ORService.php'));
}, 'App\\Controller\\SecurityController:registerAction' => function () {
    return ($this->privates['service_locator.uNPUW1B'] ?? $this->load('getServiceLocator_UNPUW1BService.php'));
}, 'App\\Controller\\UserController:index' => function () {
    return ($this->privates['service_locator.szF8V5K'] ?? $this->load('getServiceLocator_SzF8V5KService.php'));
}, 'App\\Controller\\CarsBrandController::index' => function () {
    return ($this->privates['service_locator.fSCnt1p'] ?? $this->load('getServiceLocator_FSCnt1pService.php'));
}, 'App\\Controller\\CarsModelController::index' => function () {
    return ($this->privates['service_locator.CikYYQ2'] ?? $this->load('getServiceLocator_CikYYQ2Service.php'));
}, 'App\\Controller\\SecurityController::loginAction' => function () {
    return ($this->privates['service_locator.ltE88OR'] ?? $this->load('getServiceLocator_LtE88ORService.php'));
}, 'App\\Controller\\SecurityController::registerAction' => function () {
    return ($this->privates['service_locator.uNPUW1B'] ?? $this->load('getServiceLocator_UNPUW1BService.php'));
}, 'App\\Controller\\UserController::index' => function () {
    return ($this->privates['service_locator.szF8V5K'] ?? $this->load('getServiceLocator_SzF8V5KService.php'));
})));
