<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.szF8V5K' shared service.

return $this->privates['service_locator.szF8V5K'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('userRepository' => function (): ?\App\Repository\UserRepository {
    return ($this->privates['App\Repository\UserRepository'] ?? $this->load('getUserRepositoryService.php'));
}));
