<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO9jx7xX\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO9jx7xX/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerO9jx7xX.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerO9jx7xX\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerO9jx7xX\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'O9jx7xX',
    'container.build_id' => '12f0807f',
    'container.build_time' => 1522780462,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerO9jx7xX');
