<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWuMcCP0\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWuMcCP0/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWuMcCP0.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWuMcCP0\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWuMcCP0\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WuMcCP0',
    'container.build_id' => '0520d2c5',
    'container.build_time' => 1522787624,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWuMcCP0');
